{% set component_name = "cmake" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "3.3.1" %}
{% set major_version = version.split('.')[0] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/{{ repo_name }}/archive/{{ repo_name }}{{ major_version }}_{{ version }}.tar.gz
    sha256: 5fdccb98e58dad23fcebd3ca66e43940901e3d1605132c02661db5982e55f965
    patches:
      - fixogre2respathconda.patch
      - fixfindogrenextcondaforge.patch

build:
  number: 0

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
      # dlfcn-win32 is used only for tests, we can 
      # safely ignore its run_exports
      ignore_run_exports:
        - dlfcn-win32  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
      host:
        # This is just a test-only dependency,
        # see https://github.com/gazebosim/gz-cmake/pull/334#issuecomment-1519115200
        - dlfcn-win32  # [win]
    test:
      commands:
        - test -f ${PREFIX}/share/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\share\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/share/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if exist %PREFIX%\\Library\\share\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/gazebosim/gz-cmake
  license: Apache-2.0
  license_file: LICENSE
  summary: A set of CMake modules that are used by the C++-based Gazebo projects.

extra:
  recipe-maintainers:
    - wolfv
    - traversaro
    - j-rivero
